#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

# additional binaries
#copy_exec /sbin/fsck /sbin
#copy_exec /sbin/fsck.ext4 /sbin
copy_exec /sbin/lsmod /sbin
copy_exec /sbin/losetup /sbin