#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true

# persistent storage dir
PSTORAGE_MOUNT=/mnt/storage

# persistent storage mounted ?
if mountpoint $PSTORAGE_MOUNT > /dev/null; then
    echo "persistent storage available"
else
    echo "no persistent storage available..exiting"
    exit 1
fi

# set storage writeable 
pstorage rw

# generate unique SSH Keys and store them within pstorage
# ------------------------------
echo "generating ssh host keys.."
dpkg-reconfigure openssh-server
mkdir -p $PSTORAGE_MOUNT/etc/ssh
cp /etc/ssh/ssh_host_* $PSTORAGE_MOUNT/etc/ssh

# disable service by masking it
# ------------------------------
mkdir -p $PSTORAGE_MOUNT/etc/systemd/system/
ln -s /dev/null $PSTORAGE_MOUNT/etc/systemd/system/hypersolid-firstboot.service

# set storage readonly
pstorage ro
