#!/usr/bin/env bash

set -e

export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true

# persistent storage dir
PSTORAGE_MOUNT="/mnt/storage"

# persistent storage mounted ?
if mountpoint ${PSTORAGE_MOUNT} > /dev/null; then
    echo "persistent storage available"
else
    echo "no persistent storage available..exiting"
    exit 1
fi

# set storage writeable 
pstorage rw

# generate unique SSH Keys and store them within pstorage
# ------------------------------
mkdir -p ${PSTORAGE_MOUNT}/etc/ssh
echo "generating rsa ssh host key.."
ssh-keygen -q -N "" -t rsa -b 4096 -f ${PSTORAGE_MOUNT}/etc/ssh/ssh_host_rsa_key

echo "generating ed25519 ssh host key.."
ssh-keygen -q -N "" -t ed25519 -f ${PSTORAGE_MOUNT}/etc/ssh/ssh_host_ed25519_key

# persist machine-id
# ------------------------------
echo "storing machine-id"
cp /etc/machine-id ${PSTORAGE_MOUNT}/etc/machine-id

# disable service by masking it
# ------------------------------
echo "disable hypersolid firstboot service"
mkdir -p ${PSTORAGE_MOUNT}/etc/systemd/system/
ln -s /dev/null ${PSTORAGE_MOUNT}/etc/systemd/system/hypersolid-firstboot.service

# set storage readonly
pstorage ro
